### ISSUE TITLE
About dataset preparation

### ISSUE THREAD

**Issue by dxbdxx** [Maitreyapatel/CRIPP-VQA#1]
The link https://maitreyapatel.com/CRIPP-VQA/#dataset is the precessed data or raw data? The script in dataset/ cannot run.

**Comment by Maitreyapatel** [comment]
@dxbdxx the link https://maitreyapatel.com/CRIPP-VQA/#dataset contains the raw annotations. Plus it also contains the MaskRCNN extracted features. Script inside `dataset` can only generate video from the annotation files. 

If possible, feel free to share the detailed error. I will try to help you out.

**Comment by dxbdxx** [comment]
Thanks for your reply. Now I can understand and conduct the data preparation process after modifying the script. In fact, the script _image_generation.sh_ only shows the foundamental steps and cannot run directly. The python file is _recreate.py_ instead of _recreation_v3.py_. And I also need to modify the script to process all downloaded annotations.

**Comment by Maitreyapatel** [comment]
I'm glad it is working for you. And thanks for pointing out this problem. 
Feel free to create a pull request or I will update the repo to resolve this issue as soon as possible.
